{
	"version": 1503956798,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/botnext-sheet0.png",
		"images/botnavegacion-sheet0.png",
		"images/fondos-sheet0.png",
		"images/fondos-sheet1.png",
		"images/controlador-sheet0.png",
		"images/objboton-sheet0.png",
		"images/objtexto-sheet0.png",
		"images/objtexto-sheet1.png",
		"images/objtexto-sheet2.png",
		"images/objtexto-sheet3.png",
		"images/objtexto-sheet4.png",
		"images/objtexto-sheet5.png",
		"media/clik.ogg",
		"media/correct answer.oggvorbis.ogg",
		"media/game over fx.oggvorbis.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}