{
	"version": 1516986793,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/fondo1.png",
		"images/titulos-sheet0.png",
		"images/sofia-sheet0.png",
		"images/sofia-sheet1.png",
		"images/sofia-sheet2.png",
		"images/mano1-sheet0.png",
		"images/botinicio-sheet0.png",
		"images/fondo2.png",
		"images/dialogo1-sheet0.png",
		"images/botsigu-sheet0.png",
		"images/botatra-sheet0.png",
		"images/mano2-sheet0.png",
		"images/mano3-sheet0.png",
		"images/bothome-sheet0.png",
		"images/bothome-sheet1.png",
		"images/botlapiz-sheet0.png",
		"images/botlapiz-sheet1.png",
		"images/fondo3.png",
		"images/cuadro1-sheet0.png",
		"images/cuadro1-sheet1.png",
		"images/cuadro2-sheet0.png",
		"images/cuadro2-sheet1.png",
		"images/dialogotoca-sheet0.png",
		"images/cuadrooscuro-sheet0.png",
		"images/cuadrooscuro-sheet1.png",
		"images/cuadroclaro-sheet0.png",
		"images/cuadroclaro-sheet1.png",
		"images/botoninfor1-sheet0.png",
		"images/botoninfor1-sheet1.png",
		"images/cuadbola-sheet0.png",
		"images/cuadcral-sheet0.png",
		"images/cuadcane-sheet0.png",
		"images/cuadsomb-sheet0.png",
		"images/dialo12-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/tiledbackground.png",
		"images/caragris1-sheet0.png",
		"images/caradora1-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/lapisomb1-sheet0.png",
		"images/lapi2-sheet0.png",
		"images/lapi4-sheet0.png",
		"images/lapi1-sheet0.png",
		"images/lapi3-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/estrella.png",
		"images/contador-sheet0.png",
		"images/contador-sheet1.png",
		"images/fondofelicitaciones.png",
		"images/fondomal.png",
		"images/sprite8-sheet0.png",
		"images/sprite-sheet0.png",
		"images/pared-sheet0.png",
		"images/logo_azul-sheet0.png",
		"media/pop2.m4a",
		"media/pop.m4a",
		"media/error.m4a",
		"media/campanas.m4a",
		"media/campanas.ogg",
		"media/error.ogg",
		"media/pop2.ogg",
		"media/pop.ogg",
		"media/poptext.ogg",
		"media/conteo.ogg",
		"media/tu2a-ba-p4-verde_naturaleza-02.ogg",
		"media/tu2a-ba-p4-verde_naturaleza-02.m4a",
		"media/tu2a-ba-p4-verde_naturaleza-03.ogg",
		"media/tu2a-ba-p4-verde_naturaleza-01.ogg",
		"media/tu2a-ba-p4-verde_naturaleza-03.m4a",
		"media/tu2a-ba-p4-verde_naturaleza-01.m4a",
		"media/tocaelcuadrado.m4a",
		"media/conteo.m4a",
		"media/tu2a-ba-p4-verde_naturaleza-04.m4a",
		"media/tu2a-ba-p4-verde_naturaleza-07.m4a",
		"media/tu2a-ba-p4-verde_naturaleza-07.ogg",
		"media/tu2a-ba-p4-verde_naturaleza-04.ogg",
		"media/tu2a-ba-p4-verde_naturaleza-05.m4a",
		"media/tu2a-ba-p4-verde_naturaleza-08.ogg",
		"media/tu2a-ba-p4-verde_naturaleza-09.m4a",
		"media/tocaelcuadrado.ogg",
		"media/tu2a-ba-p4-verde_naturaleza-10.m4a",
		"media/tu2a-ba-p4-verde_naturaleza-08.m4a",
		"media/tu2a-ba-p4-verde_naturaleza-09.ogg",
		"media/tu2a-ba-p4-verde_naturaleza-05.ogg",
		"media/tu2a-ba-p4-verde_naturaleza-10.ogg",
		"media/click.ogg",
		"media/aples a carrots.m4a",
		"media/aples a carrots.ogg",
		"media/arrange the colored pencils.m4a",
		"media/arrange the colored pencils.ogg",
		"media/candys soda and ships.m4a",
		"media/candys soda and ships.ogg",
		"media/congratulations.m4a",
		"media/congratulations.ogg",
		"media/green nature.m4a",
		"media/green nature.ogg",
		"media/hello my name is sofia.m4a",
		"media/hello my name is sofia.ogg",
		"media/move julieta side to side.m4a",
		"media/move julieta side to side.ogg",
		"media/try again.m4a",
		"media/try again.ogg",
		"media/we can find.m4a",
		"media/we can find.ogg",
		"media/conteo_nina.m4a",
		"media/conteo_nina.ogg",
		"media/startnina.m4a",
		"media/startnina.ogg",
		"media/touch.m4a",
		"media/touch.ogg",
		"media/vclar.m4a",
		"media/vclar.ogg",
		"media/voscuro.m4a",
		"media/voscuro.ogg",
		"icon-16.png",
		"icon-17.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-129.png",
		"icon-256.png",
		"loading-logo.png"
	]
}